/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package board.master;

import board.master.controller.GameController;
import board.master.model.input.GUIInputHandler;
import board.master.model.input.InputHandler;

public class App {

    public static void main(String[] args) {
        InputHandler inputHandler = new GUIInputHandler();
        GameController gameController = new GameController("TicTacToe", "Player", "Random", inputHandler);
        gameController.startGame();
    }
}
